-- PostgreSQL Database Dump
-- Database: ipl_db
-- Generated by SQLAlchemy


-- Table: player
DROP TABLE IF EXISTS "player" CASCADE;

CREATE TABLE "player" (Player_Id bigint, Batting_hand bigint, Bowling_skill double precision, Country_Name bigint, Player_Name text, DOB text);

-- 469 rows


-- Table: extra_runs
DROP TABLE IF EXISTS "extra_runs" CASCADE;

CREATE TABLE "extra_runs" (Match_Id bigint, Over_Id bigint, Ball_Id bigint, Extra_Type_Id bigint, Extra_Runs bigint, Innings_No bigint);

-- 7469 rows


-- Table: batsman_scored
DROP TABLE IF EXISTS "batsman_scored" CASCADE;

CREATE TABLE "batsman_scored" (Match_Id bigint, Over_Id bigint, Ball_Id bigint, Runs_Scored bigint, Innings_No bigint);

-- 133097 rows


-- Table: batting_style
DROP TABLE IF EXISTS "batting_style" CASCADE;

CREATE TABLE "batting_style" (Batting_Id bigint, Batting_hand text);

-- 2 rows


-- Table: bowling_style
DROP TABLE IF EXISTS "bowling_style" CASCADE;

CREATE TABLE "bowling_style" (Bowling_Id bigint, Bowling_skill text);

-- 14 rows


-- Table: country
DROP TABLE IF EXISTS "country" CASCADE;

CREATE TABLE "country" (Country_Id bigint, Country_Name text);

-- 12 rows


-- Table: season
DROP TABLE IF EXISTS "season" CASCADE;

CREATE TABLE "season" (Season_Id bigint, Man_of_the_Series bigint, Orange_Cap bigint, Purple_Cap bigint, Season_Year bigint);

-- 9 rows


-- Table: city
DROP TABLE IF EXISTS "city" CASCADE;

CREATE TABLE "city" (City_Id bigint, Country_id bigint, City_Name text);

-- 29 rows


-- Table: outcome
DROP TABLE IF EXISTS "outcome" CASCADE;

CREATE TABLE "outcome" (Outcome_Id bigint, Outcome_Type text);

-- 3 rows


-- Table: win_by
DROP TABLE IF EXISTS "win_by" CASCADE;

CREATE TABLE "win_by" (Win_Id bigint, Win_Type text);

-- 4 rows


-- Table: wicket_taken
DROP TABLE IF EXISTS "wicket_taken" CASCADE;

CREATE TABLE "wicket_taken" (Match_Id bigint, Over_Id bigint, Ball_Id bigint, Player_Out bigint, Kind_Out bigint, Fielders double precision, Innings_No bigint);

-- 6727 rows


-- Table: venue
DROP TABLE IF EXISTS "venue" CASCADE;

CREATE TABLE "venue" (Venue_Id bigint, City_Id bigint, Venue_Name text);

-- 35 rows


-- Table: extra_type
DROP TABLE IF EXISTS "extra_type" CASCADE;

CREATE TABLE "extra_type" (Extra_Id bigint, Extra_Name text);

-- 5 rows


-- Table: out_type
DROP TABLE IF EXISTS "out_type" CASCADE;

CREATE TABLE "out_type" (Out_Id bigint, Out_Name text);

-- 9 rows


-- Table: toss_decision
DROP TABLE IF EXISTS "toss_decision" CASCADE;

CREATE TABLE "toss_decision" (Toss_Id bigint, Toss_Name text);

-- 2 rows


-- Table: umpire
DROP TABLE IF EXISTS "umpire" CASCADE;

CREATE TABLE "umpire" (Umpire_Id bigint, Umpire_Country bigint, Umpire_Name text);

-- 52 rows


-- Table: team
DROP TABLE IF EXISTS "team" CASCADE;

CREATE TABLE "team" (Team_Id bigint, Team_Name text);

-- 13 rows


-- Table: ball_by_ball
DROP TABLE IF EXISTS "ball_by_ball" CASCADE;

CREATE TABLE "ball_by_ball" (Match_Id bigint, Over_Id bigint, Ball_Id bigint, Innings_No bigint, Team_Batting bigint, Team_Bowling bigint, Striker_Batting_Position bigint, Striker bigint, Non_Striker bigint, Bowler bigint);

-- 136590 rows


-- Table: match
DROP TABLE IF EXISTS "match" CASCADE;

CREATE TABLE "match" (Man_of_the_Match double precision, Team_1 bigint, Team_2 bigint, Match_Id bigint, Season_Id bigint, Venue_Id bigint, Toss_Winner bigint, Toss_Decide bigint, Win_Type bigint, Win_Margin double precision, Outcome_type bigint, Match_Winner double precision, Match_Date text);

-- 577 rows


-- Table: rolee
DROP TABLE IF EXISTS "rolee" CASCADE;

CREATE TABLE "rolee" (Role_Id bigint, Role_Desc text);

-- 4 rows


-- Table: player_match
DROP TABLE IF EXISTS "player_match" CASCADE;

CREATE TABLE "player_match" (Match_Id bigint, Player_Id bigint, Role_Id bigint, Team_Id bigint);

-- 12694 rows

